### ISSUE TITLE
/cd download игнорирует permissions?

### ISSUE THREAD

**Issue by omtanksam** [sub-kek/CustomDiscs-SVC#4]
Я выдал группе право "customdiscs.download", но когда человек в этой группе пытается загрузить трек, то ничего не происходит. Нет никакой ошибки. Я пытался выдать группе право "customdiscs.*", но происходит такая же проблема. При этом на меня (а я OP) эта команда реагирует.
Проблема происходит только с этой командой, например команда cd create отрабатывает как нужно.

![image](https://github.com/user-attachments/assets/1e6e6379-a4c8-4a72-b0fe-c6527498a806)
Вот так это выглядит в консоли.

**Comment by sub-kek** [comment]
Могло быть такое что выдали группе права например с кирилической "С" или "О"?

**Comment by omtanksam** [comment]
Перепроверил permission ещё раз - нет, всё корректно. Попробовал, кстати, ввести какую-то рандомную ссылку - ошибка скачивания выводится в чат, но если ввести корректную ссылку, то всё так же - ничего в чат вообще не отправляется, и трек, соответственно, не скачивается.
![image](https://github.com/user-attachments/assets/94738e05-c881-46b1-932f-0c8f6d56a152)

**Comment by sub-kek** [comment]
Какой плагин на права используйте? Сегодня проверю если ответите.

**Comment by omtanksam** [comment]
Luckperms

**Comment by sub-kek** [comment]
> Luckperms

Странно проверял все работает. Попробую еще повторить.

**Comment by omtanksam** [comment]
Если что, доп.информация: используется связка Velocity + Paper 1.21, БД Luckperms хранится локально в MariaDB

**Comment by sub-kek** [comment]
С другими плагинами же нет проблем с правами?

**Comment by omtanksam** [comment]
Неа, нет. Только с этим плагином такая проблема возникла. Причём, повторюсь, ТОЛЬКО с командой /cd download. Например, та же команда /cd create с выданными правами работает как и задумана
